CREATE TABLE TRADING_CURRENCY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATE_TIME TIMESTAMP,
    CRYPTO_DETAILS TEXT
);

-- CREATE THE USER TABLE
CREATE TABLE USER_INFO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) UNIQUE NOT NULL,
    BALANCE double,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CREATE THE TRADING_HISTORY TABLE
CREATE TABLE TRADING_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME BIGINT NOT NULL,
    TRADE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRYPTO_SYMBOL VARCHAR(20),
    TRADE_TYPE VARCHAR(10),
    QUANTITY double,
    PRICE double,
    FOREIGN KEY (USER_NAME) REFERENCES USER_INFO(ID)
);
